export const Users = [
  {
    id: 1,
    name: "Aarav Mehta",
    title: "Full Stack Developer",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    description:
      "I'm a passionate developer with 3 years of experience in building full-stack applications using MERN. I love solving problems and collaborating on innovative projects.",
    skillsOffered: ["ReactJS", "Node.js", "MongoDB"],
    skillsWanted: ["UI/UX Design", "DevOps"],
    location: "Mumbai, India",
    email: "aarav.mehta@example.com",
    phone_no: 98678987678 
  },
  {
    id: 2,
    name: "Priya Sharma",
    title: "Graphic Designer",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
    description:
      "Creative designer with 5+ years of experience in brand identity and visual communication. Now exploring backend development.",
    skillsOffered: ["Figma", "Photoshop", "Illustrator"],
    skillsWanted: ["Node.js", "Express.js"],
    location: "Delhi, India",
    email: "priya.sharma@example.com",
    phone_no: 98678987678
  },
  {
    id: 3,
    name: "Rohan Gupta",
    title: "Cloud Engineer",
    image: "https://randomuser.me/api/portraits/men/33.jpg",
    description:
      "AWS Certified professional with a knack for deploying scalable infrastructure. Looking to polish my frontend skills.",
    skillsOffered: ["AWS", "Terraform", "Docker"],
    skillsWanted: ["Tailwind CSS", "ReactJS"],
    location: "Bangalore, India",
    email: "rohan.gupta@example.com",
    phone_no: 98678987678 
  },
  {
    id: 4,
    name: "Aarav Sharma",
    title: "Frontend Developer",
    image: "https://randomuser.me/api/portraits/men/44.jpg",
    description: "React expert with 3 years of experience. Want to learn backend systems.",
    skillsOffered: ["React", "JavaScript", "CSS"],
    skillsWanted: ["Node.js", "MongoDB"],
    location: "Delhi, India",
    email: "aarav.sharma@example.com",
    phone_no: 9876543210
  },
  {
    id: 5,
    name: "Priya Mehta",
    title: "Data Analyst",
    image: "https://randomuser.me/api/portraits/women/45.jpg",
    description: "Love working with data. Curious about web development.",
    skillsOffered: ["Excel", "SQL", "Power BI"],
    skillsWanted: ["HTML", "CSS", "JavaScript"],
    location: "Mumbai, India",
    email: "priya.mehta@example.com",
    phone_no: 9812345678
  },
  {
    id: 6,
    name: "Neeraj Yadav",
    title: "Python Developer",
    image: "https://randomuser.me/api/portraits/men/46.jpg",
    description: "Built multiple Python automation scripts. Learning UI/UX.",
    skillsOffered: ["Python", "Flask", "APIs"],
    skillsWanted: ["Figma", "UX Research"],
    location: "Lucknow, India",
    email: "neeraj.yadav@example.com",
    phone_no: 9823456789
  },
  {
    id: 7,
    name: "Simran Kaur",
    title: "UI/UX Designer",
    image: "https://randomuser.me/api/portraits/women/52.jpg",
    description: "Design is my passion. Looking to learn some JavaScript.",
    skillsOffered: ["Figma", "Adobe XD", "User Research"],
    skillsWanted: ["JavaScript", "React"],
    location: "Chandigarh, India",
    email: "simran.kaur@example.com",
    phone_no: 9871234560
  },
  {
    id: 8,
    name: "Rahul Verma",
    title: "DevOps Engineer",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    description: "Kubernetes expert exploring frontend.",
    skillsOffered: ["Kubernetes", "Docker", "CI/CD"],
    skillsWanted: ["Vue.js", "React"],
    location: "Pune, India",
    email: "rahul.verma@example.com",
    phone_no: 9834567890
  },
  {
    id: 9,
    name: "Ananya Jain",
    title: "Backend Developer",
    image: "https://randomuser.me/api/portraits/women/33.jpg",
    description: "Node.js pro eager to learn about cloud platforms.",
    skillsOffered: ["Node.js", "Express", "MongoDB"],
    skillsWanted: ["AWS", "Azure"],
    location: "Noida, India",
    email: "ananya.jain@example.com",
    phone_no: 9877898765
  },
  {
    id: 10,
    name: "Ishaan Desai",
    title: "Mobile Developer",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
    description: "Flutter enthusiast. Keen on improving database skills.",
    skillsOffered: ["Flutter", "Dart", "Firebase"],
    skillsWanted: ["SQL", "PostgreSQL"],
    location: "Ahmedabad, India",
    email: "ishaan.desai@example.com",
    phone_no: 9898989898
  },
  {
    id: 11,
    name: "Sanya Kapoor",
    title: "Full Stack Developer",
    image: "https://randomuser.me/api/portraits/women/25.jpg",
    description: "Jack of all trades. Wants to explore AI now.",
    skillsOffered: ["MERN", "REST APIs", "Tailwind CSS"],
    skillsWanted: ["Python", "Machine Learning"],
    location: "Hyderabad, India",
    email: "sanya.kapoor@example.com",
    phone_no: 9765432109
  },
  {
    id: 12,
    name: "Kabir Joshi",
    title: "Cybersecurity Analyst",
    image: "https://randomuser.me/api/portraits/men/27.jpg",
    description: "Security-first thinker. Curious about frontend stacks.",
    skillsOffered: ["Pen Testing", "Nmap", "Linux"],
    skillsWanted: ["JavaScript", "React"],
    location: "Indore, India",
    email: "kabir.joshi@example.com",
    phone_no: 9753124680
  },
  {
    id: 13,
    name: "Meera Nair",
    title: "Machine Learning Engineer",
    image: "https://randomuser.me/api/portraits/women/19.jpg",
    description: "ML enthusiast seeking to understand UI better.",
    skillsOffered: ["Python", "Scikit-learn", "Pandas"],
    skillsWanted: ["HTML", "CSS", "UX Design"],
    location: "Kochi, India",
    email: "meera.nair@example.com",
    phone_no: 9701234567
  },
  {
    id: 14,
    name: "Aditya Singh",
    title: "Blockchain Developer",
    image: "https://randomuser.me/api/portraits/men/18.jpg",
    description: "Web3 developer exploring DevOps tools.",
    skillsOffered: ["Solidity", "Smart Contracts", "Ethereum"],
    skillsWanted: ["Docker", "CI/CD"],
    location: "Bhopal, India",
    email: "aditya.singh@example.com",
    phone_no: 9827654321
  },
  {
    id: 15,
    name: "Tanya Reddy",
    title: "Content Strategist",
    image: "https://randomuser.me/api/portraits/women/40.jpg",
    description: "Writing queen ready to code.",
    skillsOffered: ["Content Writing", "SEO", "Digital Strategy"],
    skillsWanted: ["HTML", "CSS", "JS"],
    location: "Visakhapatnam, India",
    email: "tanya.reddy@example.com",
    phone_no: 9745612390
  },
  {
    id: 16,
    name: "Manav Patel",
    title: "QA Tester",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
    description: "Quality is my priority. Want to learn automation.",
    skillsOffered: ["Manual Testing", "Test Cases", "Bug Reporting"],
    skillsWanted: ["Selenium", "Cypress", "JS"],
    location: "Surat, India",
    email: "manav.patel@example.com",
    phone_no: 9711123456
  },
  {
    id: 17,
    name: "Shruti Bansal",
    title: "Graphic Designer",
    image: "https://randomuser.me/api/portraits/women/37.jpg",
    description: "Illustrator lover diving into frontend development.",
    skillsOffered: ["Illustrator", "Photoshop", "Canva"],
    skillsWanted: ["HTML", "CSS", "React"],
    location: "Jaipur, India",
    email: "shruti.bansal@example.com",
    phone_no: 9755312467
  },
  {
    id: 18,
    name: "Rajeev Ranjan",
    title: "Linux Administrator",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    description: "Linux ninja. Want to build mobile apps.",
    skillsOffered: ["Linux", "Shell Scripting", "Bash"],
    skillsWanted: ["Flutter", "React Native"],
    location: "Patna, India",
    email: "rajeev.ranjan@example.com",
    phone_no: 9888776655
  },
  {
    id: 19,
    name: "Aisha Syed",
    title: "Social Media Manager",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    description: "Great at building brands. Curious about frontend dev.",
    skillsOffered: ["Instagram Marketing", "Facebook Ads", "Analytics"],
    skillsWanted: ["HTML", "JavaScript"],
    location: "Lucknow, India",
    email: "aisha.syed@example.com",
    phone_no: 9764567890
  },
  {
    id: 20,
    name: "Nikhil Chandra",
    title: "Full Stack Developer",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    description: "Working in Django + React. Exploring DevOps now.",
    skillsOffered: ["Django", "React", "PostgreSQL"],
    skillsWanted: ["Docker", "Kubernetes"],
    location: "Ranchi, India",
    email: "nikhil.chandra@example.com",
    phone_no: 9745123456
  },
  {
    id: 21,
    name: "Zoya Khan",
    title: "HR Recruiter",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
    description: "Hiring expert eager to dive into data analytics.",
    skillsOffered: ["Recruitment", "Interviewing", "HR Tech"],
    skillsWanted: ["Excel", "SQL", "Tableau"],
    location: "Nagpur, India",
    email: "zoya.khan@example.com",
    phone_no: 9734561234
  },
  {
    id: 22,
    name: "Harshit Malhotra",
    title: "Automation Engineer",
    image: "https://randomuser.me/api/portraits/men/36.jpg",
    description: "Automation is my forte. Want to build personal projects.",
    skillsOffered: ["Selenium", "Python", "Test Automation"],
    skillsWanted: ["React", "Firebase"],
    location: "Gurgaon, India",
    email: "harshit.malhotra@example.com",
    phone_no: 9712345678
  },
  {
    id: 23,
    name: "Nandini Roy",
    title: "Frontend Intern",
    image: "https://randomuser.me/api/portraits/women/35.jpg",
    description: "Learning React. Want to work on real projects.",
    skillsOffered: ["HTML", "CSS", "Bootstrap"],
    skillsWanted: ["React", "API Integration"],
    location: "Kolkata, India",
    email: "nandini.roy@example.com",
    phone_no: 9799999999
  },
  {
    id: 21,
    name: "Ayesha Khan",
    title: "Frontend Developer",
    image: "https://randomuser.me/api/portraits/women/21.jpg",
    description: "React enthusiast looking to dive into backend development.",
    skillsOffered: ["HTML", "CSS", "ReactJS"],
    skillsWanted: ["Node.js", "MongoDB"],
    location: "Mumbai, India",
    email: "ayesha.khan@example.com",
    phone_no: 9876543210
  },
  {
    id: 22,
    name: "Kunal Verma",
    title: "Backend Developer",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
    description: "Passionate about server-side development and REST APIs.",
    skillsOffered: ["Node.js", "Express", "PostgreSQL"],
    skillsWanted: ["React", "UI/UX"],
    location: "Delhi, India",
    email: "kunal.verma@example.com",
    phone_no: 9876543211
  },
  {
    id: 23,
    name: "Sneha Rao",
    title: "Data Scientist",
    image: "https://randomuser.me/api/portraits/women/23.jpg",
    description: "Enjoys making sense of data. Wants to build full-stack apps.",
    skillsOffered: ["Python", "Pandas", "Machine Learning"],
    skillsWanted: ["ReactJS", "Node.js"],
    location: "Hyderabad, India",
    email: "sneha.rao@example.com",
    phone_no: 9876543212
  },
  {
    id: 24,
    name: "Ankit Sharma",
    title: "DevOps Engineer",
    image: "https://randomuser.me/api/portraits/men/24.jpg",
    description: "Loves CI/CD pipelines and automation.",
    skillsOffered: ["Docker", "Kubernetes", "Jenkins"],
    skillsWanted: ["JavaScript", "Next.js"],
    location: "Chandigarh, India",
    email: "ankit.sharma@example.com",
    phone_no: 9876543213
  },
  {
    id: 25,
    name: "Neha Singh",
    title: "Full Stack Developer",
    image: "https://randomuser.me/api/portraits/women/25.jpg",
    description: "Comfortable with both frontend and backend.",
    skillsOffered: ["React", "Node.js", "MongoDB"],
    skillsWanted: ["AWS", "DevOps"],
    location: "Pune, India",
    email: "neha.singh@example.com",
    phone_no: 9876543214
  },
  {
    id: 26,
    name: "Rajeev Menon",
    title: "UI/UX Designer",
    image: "https://randomuser.me/api/portraits/men/26.jpg",
    description: "Focuses on clean and usable interfaces.",
    skillsOffered: ["Figma", "Adobe XD", "Design Thinking"],
    skillsWanted: ["HTML", "CSS", "JavaScript"],
    location: "Kochi, India",
    email: "rajeev.menon@example.com",
    phone_no: 9876543215
  },
  {
    id: 27,
    name: "Pooja Bansal",
    title: "Content Strategist",
    image: "https://randomuser.me/api/portraits/women/27.jpg",
    description: "Good with words. Learning about marketing automation.",
    skillsOffered: ["Content Writing", "SEO", "Marketing"],
    skillsWanted: ["JavaScript", "React"],
    location: "Jaipur, India",
    email: "pooja.bansal@example.com",
    phone_no: 9876543216
  },
  {
    id: 28,
    name: "Vikram Iyer",
    title: "Cybersecurity Analyst",
    image: "https://randomuser.me/api/portraits/men/28.jpg",
    description: "Security-focused professional exploring app development.",
    skillsOffered: ["Ethical Hacking", "Network Security", "Linux"],
    skillsWanted: ["JavaScript", "Node.js"],
    location: "Ahmedabad, India",
    email: "vikram.iyer@example.com",
    phone_no: 9876543217
  },
  {
    id: 29,
    name: "Divya Mehta",
    title: "Mobile App Developer",
    image: "https://randomuser.me/api/portraits/women/29.jpg",
    description: "Experienced in Flutter. Curious about backend tech.",
    skillsOffered: ["Flutter", "Dart", "Firebase"],
    skillsWanted: ["Express", "MongoDB"],
    location: "Lucknow, India",
    email: "divya.mehta@example.com",
    phone_no: 9876543218
  },
  {
    id: 30,
    name: "Arjun Desai",
    title: "Game Developer",
    image: "https://randomuser.me/api/portraits/men/30.jpg",
    description: "Game dev with Unity, expanding into full-stack web apps.",
    skillsOffered: ["Unity", "C#", "Game Design"],
    skillsWanted: ["ReactJS", "Node.js"],
    location: "Nagpur, India",
    email: "arjun.desai@example.com",
    phone_no: 9876543219
  },
  {
    id: 31,
    name: "Tanvi Joshi",
    title: "AI Engineer",
    image: "https://randomuser.me/api/portraits/women/31.jpg",
    description: "Works with neural networks and natural language processing.",
    skillsOffered: ["Python", "TensorFlow", "NLP"],
    skillsWanted: ["JavaScript", "Frontend"],
    location: "Bhopal, India",
    email: "tanvi.joshi@example.com",
    phone_no: 9876543220
  },
  {
    id: 32,
    name: "Aditya Chauhan",
    title: "Cloud Architect",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    description: "Helps companies migrate to the cloud.",
    skillsOffered: ["AWS", "Azure", "GCP"],
    skillsWanted: ["Node.js", "GraphQL"],
    location: "Indore, India",
    email: "aditya.chauhan@example.com",
    phone_no: 9876543221
  },
  {
    id: 33,
    name: "Meera Patel",
    title: "QA Engineer",
    image: "https://randomuser.me/api/portraits/women/33.jpg",
    description: "Writes tests and ensures bug-free releases.",
    skillsOffered: ["Selenium", "Postman", "Manual Testing"],
    skillsWanted: ["JavaScript", "Cypress"],
    location: "Rajkot, India",
    email: "meera.patel@example.com",
    phone_no: 9876543222
  },
  {
    id: 34,
    name: "Siddharth Jain",
    title: "Blockchain Developer",
    image: "https://randomuser.me/api/portraits/men/34.jpg",
    description: "Builds dApps and smart contracts on Ethereum.",
    skillsOffered: ["Solidity", "Web3.js", "Ethereum"],
    skillsWanted: ["Node.js", "MongoDB"],
    location: "Surat, India",
    email: "siddharth.jain@example.com",
    phone_no: 9876543223
  },
  {
    id: 35,
    name: "Ishita Sharma",
    title: "Marketing Analyst",
    image: "https://randomuser.me/api/portraits/women/35.jpg",
    description: "Analyzes campaign performance and user data.",
    skillsOffered: ["Google Analytics", "Excel", "SQL"],
    skillsWanted: ["Python", "Power BI"],
    location: "Varanasi, India",
    email: "ishita.sharma@example.com",
    phone_no: 9876543224
  },
  {
    id: 36,
    name: "Ravi Dubey",
    title: "Technical Writer",
    image: "https://randomuser.me/api/portraits/men/35.jpg",
    description: "Writes docs for complex technical concepts.",
    skillsOffered: ["Technical Writing", "Markdown", "Git"],
    skillsWanted: ["JavaScript", "ReactJS"],
    location: "Patna, India",
    email: "ravi.dubey@example.com",
    phone_no: 9876543225
  },
  {
    id: 37,
    name: "Simran Kaur",
    title: "Software Engineer",
    image: "https://randomuser.me/api/portraits/women/36.jpg",
    description: "Full-stack engineer excited about open-source.",
    skillsOffered: ["Java", "Spring Boot", "MySQL"],
    skillsWanted: ["React", "Tailwind CSS"],
    location: "Amritsar, India",
    email: "simran.kaur@example.com",
    phone_no: 9876543226
  },
  {
    id: 38,
    name: "Mohit Rathi",
    title: "ML Engineer",
    image: "https://randomuser.me/api/portraits/men/36.jpg",
    description: "Specializes in predictive modeling.",
    skillsOffered: ["Scikit-learn", "Pandas", "Python"],
    skillsWanted: ["React", "MongoDB"],
    location: "Noida, India",
    email: "mohit.rathi@example.com",
    phone_no: 9876543227
  },
  {
    id: 39,
    name: "Ananya Kapoor",
    title: "Product Manager",
    image: "https://randomuser.me/api/portraits/women/37.jpg",
    description: "Manages product lifecycles and user stories.",
    skillsOffered: ["Agile", "Jira", "User Research"],
    skillsWanted: ["Figma", "Design"],
    location: "Gurgaon, India",
    email: "ananya.kapoor@example.com",
    phone_no: 9876543228
  },
  {
    id: 40,
    name: "Dhruv Nair",
    title: "Data Analyst",
    image: "https://randomuser.me/api/portraits/men/37.jpg",
    description: "Good at drawing insights from large datasets.",
    skillsOffered: ["Excel", "SQL", "Power BI"],
    skillsWanted: ["Python", "Flask"],
    location: "Thiruvananthapuram, India",
    email: "dhruv.nair@example.com",
    phone_no: 9876543229
  },
  {
    id: 41,
    name: "Priya Sharma",
    title: "Yoga Instructor",
    image: "https://randomuser.me/api/portraits/women/41.jpg",
    description: "Certified yoga trainer passionate about mindfulness and holistic health.",
    skillsOffered: ["Yoga", "Meditation"],
    skillsWanted: ["Web Development", "Canva"],
    location: "Delhi, India",
    email: "priya.sharma@example.com",
    phone_no: 9876543210
  },
  {
    id: 42,
    name: "Ankit Verma",
    title: "Content Writer",
    image: "https://randomuser.me/api/portraits/men/42.jpg",
    description: "Writes SEO-friendly blogs and articles. Keen to learn coding basics.",
    skillsOffered: ["Content Writing", "Copywriting"],
    skillsWanted: ["HTML", "CSS"],
    location: "Pune, India",
    email: "ankit.verma@example.com",
    phone_no: 9823412345
  },
  {
    id: 43,
    name: "Megha Joshi",
    title: "Fashion Designer",
    image: "https://randomuser.me/api/portraits/women/43.jpg",
    description: "Freelance designer, excited to explore the world of e-commerce.",
    skillsOffered: ["Fashion Design", "Sketching"],
    skillsWanted: ["Shopify", "ReactJS"],
    location: "Mumbai, India",
    email: "megha.joshi@example.com",
    phone_no: 9811122233
  },
  {
    id: 44,
    name: "Siddharth Mehra",
    title: "Full Stack Developer",
    image: "https://randomuser.me/api/portraits/men/44.jpg",
    description: "MERN stack developer interested in public speaking.",
    skillsOffered: ["Node.js", "MongoDB", "React"],
    skillsWanted: ["Public Speaking", "Leadership"],
    location: "Hyderabad, India",
    email: "siddharth.mehra@example.com",
    phone_no: 9900022233
  },
  {
    id: 45,
    name: "Ritu Jain",
    title: "Freelance Illustrator",
    image: "https://randomuser.me/api/portraits/women/45.jpg",
    description: "Creates digital art, now diving into UI/UX design.",
    skillsOffered: ["Illustration", "Digital Art"],
    skillsWanted: ["Figma", "UI/UX Design"],
    location: "Ahmedabad, India",
    email: "ritu.jain@example.com",
    phone_no: 9933312312
  },
  {
    id: 46,
    name: "Abhinav Singh",
    title: "Chef",
    image: "https://randomuser.me/api/portraits/men/46.jpg",
    description: "Professional chef who loves experimenting with global cuisine.",
    skillsOffered: ["Cooking", "Baking"],
    skillsWanted: ["Photography", "Instagram Marketing"],
    location: "Chennai, India",
    email: "abhinav.singh@example.com",
    phone_no: 9998887766
  },
  {
    id: 47,
    name: "Simran Kaur",
    title: "School Teacher",
    image: "https://randomuser.me/api/portraits/women/47.jpg",
    description: "Passionate about teaching and learning new digital tools.",
    skillsOffered: ["Teaching", "Grammar"],
    skillsWanted: ["Canva", "Google Sheets"],
    location: "Ludhiana, India",
    email: "simran.kaur@example.com",
    phone_no: 9812312131
  },
  {
    id: 48,
    name: "Raghav Arora",
    title: "Digital Marketer",
    image: "https://randomuser.me/api/portraits/men/48.jpg",
    description: "Handles paid campaigns, wants to upskill in graphic design.",
    skillsOffered: ["SEO", "Google Ads", "Meta Ads"],
    skillsWanted: ["Figma", "Adobe Illustrator"],
    location: "Jaipur, India",
    email: "raghav.arora@example.com",
    phone_no: 9877878787
  },
  {
    id: 49,
    name: "Nisha Patel",
    title: "Photographer",
    image: "https://randomuser.me/api/portraits/women/49.jpg",
    description: "Loves capturing stories through her lens.",
    skillsOffered: ["Photography", "Photo Editing"],
    skillsWanted: ["Video Editing", "Web Design"],
    location: "Surat, India",
    email: "nisha.patel@example.com",
    phone_no: 9786543211
  },
  {
    id: 50,
    name: "Kunal Thakur",
    title: "Sales Executive",
    image: "https://randomuser.me/api/portraits/men/50.jpg",
    description: "Communicates with clients, wants to learn automation tools.",
    skillsOffered: ["Sales", "Negotiation"],
    skillsWanted: ["Zapier", "Google Scripts"],
    location: "Noida, India",
    email: "kunal.thakur@example.com",
    phone_no: 9988776655
  },
  {
    id: 51,
    name: "Deepika Reddy",
    title: "Life Coach",
    image: "https://randomuser.me/api/portraits/women/51.jpg",
    description: "Helps people with mindset shifts, curious about tech.",
    skillsOffered: ["Life Coaching", "Mindfulness"],
    skillsWanted: ["No-Code Tools", "Notion"],
    location: "Hyderabad, India",
    email: "deepika.reddy@example.com",
    phone_no: 9988771122
  },
  {
    id: 52,
    name: "Harsh Vardhan",
    title: "UI/UX Designer",
    image: "https://randomuser.me/api/portraits/men/52.jpg",
    description: "Designs intuitive apps, looking to learn photography.",
    skillsOffered: ["Figma", "User Research"],
    skillsWanted: ["DSLR Photography", "Lighting"],
    location: "Gurgaon, India",
    email: "harsh.vardhan@example.com",
    phone_no: 9922334455
  },
  {
    id: 53,
    name: "Sneha Dubey",
    title: "Nutritionist",
    image: "https://randomuser.me/api/portraits/women/53.jpg",
    description: "Certified nutritionist, exploring content creation.",
    skillsOffered: ["Diet Planning", "Healthy Eating"],
    skillsWanted: ["Reels Editing", "YouTube Scripting"],
    location: "Indore, India",
    email: "sneha.dubey@example.com",
    phone_no: 9887654321
  },
  {
    id: 54,
    name: "Ramesh Yadav",
    title: "Mechanical Engineer",
    image: "https://randomuser.me/api/portraits/men/54.jpg",
    description: "Works in automation, learning website development.",
    skillsOffered: ["AutoCAD", "SolidWorks"],
    skillsWanted: ["HTML", "CSS", "JavaScript"],
    location: "Nagpur, India",
    email: "ramesh.yadav@example.com",
    phone_no: 9845612345
  },
  {
    id: 55,
    name: "Tanya Kapoor",
    title: "Dance Choreographer",
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    description: "Bollywood dancer, wants to build an online presence.",
    skillsOffered: ["Dance", "Stage Presence"],
    skillsWanted: ["Instagram Growth", "Video Editing"],
    location: "Bhopal, India",
    email: "tanya.kapoor@example.com",
    phone_no: 9812212211
  },
  {
    id: 56,
    name: "Aman Sheikh",
    title: "Finance Consultant",
    image: "https://randomuser.me/api/portraits/men/56.jpg",
    description: "Helps manage personal finances. Curious about app design.",
    skillsOffered: ["Budgeting", "Investments"],
    skillsWanted: ["Figma", "UX Principles"],
    location: "Kolkata, India",
    email: "aman.sheikh@example.com",
    phone_no: 9977998888
  },
  {
    id: 57,
    name: "Pooja Nair",
    title: "HR Manager",
    image: "https://randomuser.me/api/portraits/women/57.jpg",
    description: "Experienced in hiring, now learning agile and Scrum.",
    skillsOffered: ["HR", "Recruiting"],
    skillsWanted: ["Scrum", "Agile Methodology"],
    location: "Bangalore, India",
    email: "pooja.nair@example.com",
    phone_no: 9877898765
  },
  {
    id: 58,
    name: "Naveen Rao",
    title: "Electrician",
    image: "https://randomuser.me/api/portraits/men/58.jpg",
    description: "On-field expert in wiring & circuits. Exploring mobile repair.",
    skillsOffered: ["Wiring", "Electrical Installation"],
    skillsWanted: ["Mobile Repair", "Basic Coding"],
    location: "Patna, India",
    email: "naveen.rao@example.com",
    phone_no: 9765432188
  },
  {
    id: 59,
    name: "Neha Bansal",
    title: "Baker",
    image: "https://randomuser.me/api/portraits/women/59.jpg",
    description: "Creates artisan cakes and cupcakes. Curious about online selling.",
    skillsOffered: ["Baking", "Cake Decoration"],
    skillsWanted: ["E-commerce", "Instagram Ads"],
    location: "Lucknow, India",
    email: "neha.bansal@example.com",
    phone_no: 9988123412
  },
  {
    id: 60,
    name: "Gautam Sharma",
    title: "Personal Trainer",
    image: "https://randomuser.me/api/portraits/men/60.jpg",
    description: "Helps clients get fit. Wants to make fitness videos.",
    skillsOffered: ["Fitness Training", "Diet Plans"],
    skillsWanted: ["Video Production", "Canva"],
    location: "Delhi, India",
    email: "gautam.sharma@example.com",
    phone_no: 9812345678
  }
];
